tags:
- 'coma'
- 'google-cloud-datastore-util'

timeout: "900s"

steps:
# Start by downloading a cache of the m2 repository
# If it is not available then create an empty m2 directory
- name: "gcr.io/kramphub-toolshed-shared/docker-maven-dependency-cache"
  id: "download-maven-cache"
  env:
  - STAGE=download
  - BUCKET=coma-m2
  - CACHE_NAME=google-cloud-datastore-util.tar

# Get the Kiya configuration for shared secrets
- name: "gcr.io/cloud-builders/gsutil"
  id: "get-kiya-config"
  args: ["cp", "gs://kramphub-kiya-config/kiya.config", "kiya.config"]

# Get the settings.xml for Maven and store it in a file
- name: "gcr.io/kramphub-toolshed-shared/github-kramphub-kiya:stable"
  id: "get-mvn-settings"
  args: ["-c", "kiya.config",
         "-o", "util/settings.xml",
         "shared", "get" , "jfrog/cd-pipeline/settings-deploy"
  ]

# build jar
- name: 'eu.gcr.io/kramphub-toolshed-shared/mvn'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pwd
    ls -al
    cd util
    if [ -z "$TAG_NAME" ]; then
      mvn -s settings.xml compile
    else
      mvn -s settings.xml versions:set -DnewVersion=${TAG_NAME}
      mvn -s settings.xml deploy
    fi

  # Upload the m2 cache
- name: "gcr.io/kramphub-toolshed-shared/docker-maven-dependency-cache"
  id: "upload-maven-cache"
  env:
  - STAGE=upload
  - BUCKET=coma-m2
  - CACHE_NAME=google-cloud-datastore-util.tar
